version: 38
jobs:
- name: Build for x86_64
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: true
    withSubmodules: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build everything
    runInContainer: true
    image: onedev.site.tesses.net/crosslang/crosslang:latest
    interpreter: !DefaultInterpreter
      commands: |
        bash ./pack.sh
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish shell package
    artifacts: Tesses.CrossLang.ShellPackage-*.crvm
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish Package Server
    sourcePath: Tesses.CrossLang.PackageServer/bin/
    artifacts: Tesses.CrossLang.PackageServer-*.crvm
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish Website Package
    sourcePath: Tesses.CrossLang.WebSite/bin
    artifacts: Tesses.CrossLang.WebSite-*.crvm
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: Build container
    dockerfile: Dockerfile
    output: !RegistryOutput
      tags: onedev.site.tesses.net/crosslang/crosslangextras/crosslangextras:latest
    registryLogins:
    - registryUrl: '@server_url@'
      userName: '@job_token@'
      passwordSecret: dockersecret
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !DependencyFinishedTrigger
    projects: crosslang
  - !BranchUpdateTrigger
    branches: master
    projects: crosslang/crosslangextras
  projectDependencies:
  - projectPath: crosslang
    buildProvider: !LastFinishedBuild
      jobName: Build for x86_64
    artifacts: -**
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
